<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'de9f862b910641af950114116ff4a94d',
  'DATABASE_URL' => 'mysql://citevewp_specimen:specimen2020@127.0.0.1:3306/citevewp_citeservices?',
  /*'MAILER_DSN' => 'gmail://csciteservices@gmail.com:Specimen@default',
  'MAILER_URL' => 'smtp://mail.citeservices.yo.fr:465?encryption=ssl&auth_mode=login&username=contact@citeservices.yo.fr&password=specimen2020**+A',*/
);
